export enum Params {
  // IDS
  idCharacter = 'idCharacter',
  idCharacterCostume = 'idCharacterCostume',
  idGame = 'idGame',
  idMode = 'idMode',
  idMiniGame = 'idMiniGame',
  idPlatform = 'idPlatform',
  idPlayer = 'idPlayer',
  idStage = 'idStage',
  idScore = 'idScore',
  idScoreApprovalMotive = 'idScoreApprovalMotive',
  idScoreStatus = 'idScoreStatus',
  idSteamProfile = 'idSteamProfile',
  idUser = 'idUser',
  idPlatforms = 'idPlatforms',
  idGames = 'idGames',
  idMiniGames = 'idMiniGames',
  idModes = 'idModes',
  idStages = 'idStages',
  idRule = 'idRule',
  idCharacterCostumes = 'idCharacterCostumes',
  idPlayersSelected = 'idPlayersSelected',
  idNotification = 'idNotification',

  // OTHERS
  steamid = 'steamid',
  personaName = 'personaName',
  email = 'email',
  orderBy = 'orderBy',
  orderByDirection = 'orderByDirection',
  confirmationCode = 'confirmationCode',
  openidReturnTo = 'openid.return_to',
  uuid = 'uuid',
  username = 'username',
  action = 'action',
  limit = 'limit',
  page = 'page',
  url = 'url',
  term = 'term',
  status = 'status',
  fromDate = 'fromDate',
  toDate = 'toDate',
  type = 'type',
  worldRecord = 'worldRecord',
  characterWorldRecord = 'characterWorldRecord',
  combinationWorldRecord = 'combinationWorldRecord',
  score = 'score',
  usernameOrEmail = 'usernameOrEmail',
  key = 'key',
}

export enum HeaderParams {
  authorizationSteam = 'authorization-steam',
}
